### ISSUE TITLE
Patoline status ?

### ISSUE THREAD

**Issue by zejal** [patoline/patoline#1]
Hello,
Is this source code repository the official one for Patoline project please ? I'd like to experiment a bit with Patoline to see how easy it is to typeset with lettrines (as PDF), put notes in margins, or typeset first line of some paragraphs with a different font for example but unsure if it's actively maintained at the moment.

Can Patoline be built on Windows ?

Thanks
Best regards
J

**Comment by rlepigre** [comment]
Hi there,

This is indeed the official repository of the Patoline project, but the website has probably not been updated recently. Patoline cannot be built on Windows, and I'm not sure any of the main developers will ever make an effort in this direction.

What you want to do can be done, but there is not yet any high-level support for notes in margins, and I don't think anyone eved tried typesetting with lettrines in Patoline. Again, all of these things can be done, but they will require a fair amount of OCaml programming (at least for the side notes) if you want some automation.

Note that using a different font for the first line only will require computing a kind of fixed-point, since the change of size in the font may induce different hyphenation points.

Cheers,
Rodolphe

**Comment by zejal** [comment]
Hi, 
Glad to see that patoline is alive and kicking.
I've cloned the patoline repository locally.
I've installed OCaml 4.06 from instructions https://fdopen.github.io/opam-repository-mingw/installation/ but when I run "make configure" in main patoline directory I get the following error:
$ make configure
[OPT] -> configure
File "configure.ml", line 43, characters 25-28:
Error: This expression has type bytes but an expression was expected of type
         string
make: *** [GNUmakefile:80: configure] Error 2

Thanks
Regards
Joseph

**Comment by rlepigre** [comment]
This is due to the "safe-string" option being activated by default on OCaml 4.06 (we did not yet applied the necessary changes). A workaround is to work with 0Caml 4.05, which works fine on my machine. Note that you will need to install the following dependencies for Patoline (the main website is not up to date):

- https://github.com/rlepigre/ocaml-earley
- https://github.com/rlepigre/ocaml-earley-ocaml
- https://github.com/rlepigre/ocaml-imagelib


Feel free to ask for more details if you need.

Cheers,
Rodolphe

**Comment by zejal** [comment]
Thanks, I use the installer from the page I linked above, and I do not see any way to use an older version of OCaml (it does not ask for any version) :(

Can I get the listed dependencies using OPAM ? I see imagelib and earley in opam list -a output. But I do not see ocaml-earley-ocaml.

Thanks again
Regards

**Comment by rlepigre** [comment]
OK, I'll try to fix 4.06 installation this week.

You can get imagelib on opam, earley and earley-ocaml might not be available for ocaml 4.06 yet. However, you can install them from their repository.

Apart from theses, you will only need camlzip and sqlite3 for patoline to produce PDFs. Fontconfig is not mandatory (I am not using it) and cairo is only used for the cairo driver (that is not really useful, rather a toy driver).

**Comment by zejal** [comment]
Cool thanks a lot. Regarding 4.06 there is no emergency at all. I could install 4.06 compiler without safe string and it works all fine. I'll install then sqllite3 which is the only missing bit.

**Comment by zejal** [comment]
Apparenlty mysql is also required, otherwise I get an error in src/db/Db.ml.
line 419, characters 85-93:
Error: Unbound value log_name
Rules.mk:193: recipe for target 'src/db/Db.cmo' failed

Why do we need sqlite3 for PDF ? I'd imagine it's required for bibliography only.
Thanks

**Comment by rlepigre** [comment]
Sqlite3 is also used for unicode stuff. Mysql should be optional, this "bug" has probably been introduced recently, I'll investigate when I have a moment.

**Comment by sid-kap** [comment]
BTW, it looks like http://patoline.org is down...

**Comment by flh** [comment]
The "unbound log_name" issue should be fixed by commit 527fb612f5e830a8448a667ac72a06f206ef5dc6

**Comment by zejal** [comment]
Awesome, I am able to build much more files, but I get another error now:

[BYT] src/Drivers/SVG/SVG.cmo
File "src/Drivers/SVG/SVG.ml", line 691, characters 19-868:
Error: This expression has type
         ('a -> 'b, unit, string, string, string, 'a -> 'b)
         CamlinternalFormatBasics.fmt
       but an expression was expected of type
         ('a -> 'b, unit, string, string, string, string)
         CamlinternalFormatBasics.fmt
       Type 'a -> 'b is not compatible with type string
Rules.mk:193: recipe for target 'src/Drivers/SVG/SVG.cmo' failed

**Comment by flh** [comment]
I have no OCaml 4.06 installation for the moment in order to test, but I expect this bug to be fixed by 98a3491aa543cb458964e6ec29bce0a5e3c571c5
(4.06 became more strict by default on formats. We could temporarily add -no-strict-formats switch to ocamlc but it seems preferable to update format strings.)

**Comment by rlepigre** [comment]
Speaking of which, Patoline is now compatible with 4.06, including the safe-string feature (enabled by default).

**Comment by zejal** [comment]
Great, thanks a lot. Will sync and have a try ASAP.

**Comment by flh** [comment]
The reported position (character 19-868) starts from the beginning of the format given to sprintf to somewhere in the middle of the format string (somewhere at line 720, on the "e" of getEl**e**mentById in JS function setReaction).

I do not understand why the format is being split there by the compiler. @relpigre, do you think it would be worth investigating whether it is a parsing error in pa_ocaml?

**Comment by rlepigre** [comment]
Yep, looks like we have an ambiguity. I'm investigating (https://github.com/rlepigre/ocaml-earley-ocaml/issues/5). What's weird is that I do not have this bug on my machine, although the parser is still ambiguous.

**Comment by zejal** [comment]
Sure. stdout file
[SVG_pa_ocaml.ml.txt](https://github.com/patoline/patoline/files/1687041/SVG_pa_ocaml.ml.txt)
stderr file is empty.

**Comment by rlepigre** [comment]
That's a classic... `\r\n` on Windows!

**Comment by rlepigre** [comment]
Could you try https://github.com/rlepigre/ocaml-earley-ocaml with the last patch (0c40879fa8c19d3294581c9d210039f8d2978d95)?

**Comment by zejal** [comment]
Still no luck I am afraid. If I replace the lengthy format string with simple "%d %d %d %d %d" in line 702 it compiles. Could it be an issue with format string that confuses CamlinternalFormatBasics.fmt ?

**Comment by rlepigre** [comment]
OK, there is definitely some parsing problem going on, but it does not seem to come from `pa_ocaml` or `pa_patoline` since the source file is not processed with these tools. Does the following command work, from the root of the patoline directory, after the make fails?

`ocamlfind ocamlc -I src/Drivers/SVG -I src/Typography -I src/patfonts -I src/patutil -I src/rawlib -I src/unicodelib -o src/Drivers/SVG/SVG.cmo -c src/Drivers/SVG/SVG.ml`

@flh do you think that the problem could come from `cpp`?

**Comment by zejal** [comment]
If I append with \ all lines in the format (between the double quotes) SVG.ml builds fine. From OCaml doc [http://caml.inria.fr/pub/docs/manual-ocaml/lex.html](url): 

> To allow splitting long string literals across lines, the sequence \newline spaces-or-tabs (a backslash at the end of a line followed by any number of spaces and horizontal tabulations at the beginning of the next line) is ignored inside string literals.

**Comment by zejal** [comment]
Also made similar change in src/Drivers/Patonet/Patonet.ml line 387-817 (added \ at end of lines in format). Another error I see is 

[UNI] src/unicodelib/UnicodeData.data
Parse error: file "src/unicodelib/data/UnicodeData.txt", line 1, character 37.
Could be linked to DOS \r\n line endings.

**Comment by flh** [comment]
cpp could interfere because the format contains a C-style comment at line 718 (which is extremely close to the position of the error reported by @zejal. cpp probably does not understand the multi-line string literal and parse the comment delimiters, or even try and close the string literal.

If this is the case, it might be a good reason to get rid of cpp.

**Comment by zejal** [comment]
If I remove the C-style comment at line 718 SVG.ml builds fine.

**Comment by rlepigre** [comment]
I agree that we should get rid of `cpp`, a first step could be to not call it whenever it is not
necessary. I though that's what we were used to do, wasn't it @flh?

**Comment by rlepigre** [comment]
OK @zejal, we have identified the problem, we will just stop using `cpp` on these files.

For your other problem with `UnicodeData.txt`, can you try to change line 159 of file `src/unicodelib/pa_UnicodeData.ml` from

`    titlecase:code? '\n' ->`

to

`    titlecase:code? '\r'? '\n' ->`

If that works, I'll push a fix. Sorry, I can't try it since I don't have access to a machine with Windows.

**Comment by zejal** [comment]
Works all fine, changed in line 159, 195 and 210.

**Comment by zejal** [comment]
BTW after this changes (removed /* */ comments in SVG.ml and Patonet.ml + in pa_UnicodeData.ml)  patoline builds complete successfully. 
Thanks a lot for your help.

**Comment by zejal** [comment]
Actually after having switched to 4.06.0 from 4.06.0+unsafe_string I get an error I have not seen before

Error: Files /home/jo/.opam/4.06.0/lib/earley_ocaml/earley_ocaml.cmxa
       and /home/jo/.opam/4.06.0/lib/ocaml/compiler-libs/ocamlcommon.cmxa
       make inconsistent assumptions over implementation Ast_helper

**Comment by rlepigre** [comment]
Yes @zejal, it is always safer to call `make distclean` when you change OCaml version.

Thanks for the feedback on `src/unicodelib/pa_UnicodeData.ml`, I applied the changes in 0e90532a08db4e76f9923e6a5b359291a69f1c6b.

**Comment by rlepigre** [comment]
Patoline should now be installable without any modifications for you @zejal (with f658c1f74e1a53b8ec1606ffcb3f1fab4d19e152). I temporarily fixed the C-like comment issue.

**Comment by zejal** [comment]
Thanks a lot / merci ! Will have a try, and soon play with patoline :-)

**Comment by rlepigre** [comment]
Cool, let us know if you need more help! Have fun! :-)

**Comment by zejal** [comment]
Thanks. I am trying building .txp files from tests and examples. Some work fine, others do not. 
Notre_Dame_de_Paris_Hugo.txp fails with: "ocamlopt.opt got signal and exited" error.
long_par.txp takes very long time and more than 1GB of memory (actually killed it before it completed).
Others have syntax error when building them.
What's the recommended way to get started with patoline please? For now I can typeset very simple text. As said in my first comment I'd like to hopefully typeset similar texts as I do currently with ConTeXt/luatex. I see/hope Patoline as being a modern, more robust alternative to TeX.

**Comment by flh** [comment]
I also get a stack overflow when building too large Patoline documents. The OCaml compiler is not tail recursive, and we quickly push it beyond its limits with patoline. For the moment, the workaround is to increase the stack size (using ulimit on Unices), but we should definitely change the output of pa_patoline to prevent this.
