### ISSUE TITLE
Unbound module with a relative path

### ISSUE THREAD

**Issue by ghuysmans** [patoline/patoline#17]
OCaml build fails when referring to the input using a relative path, `-I .patobuild` should be `-I examples/.patobuild` to match the output path:
```
~/prog/patoline$ patoline examples/hello_world.txp 
[PPP] pa_patoline --main --build-dir examples/.patobuild examples/hello_world.txp > examples/.patobuild/hello_world.ml
[DEP] ocamldep -I . -one-line -native -ml-synonym .txp examples/.patobuild/hello_world_.ml
[OPT] ocamlfind ocamlopt -package patoline.patoraw,patoline.typography,patoline.format.DefaultFormat,earley,earley.str,patoline.driver.Pdf -I .patobuild -c -o examples/.patobuild/hello_world_.cmx examples/.patobuild/hello_world_.ml
File "examples/.patobuild/hello_world_.ml", line 22, characters 15-35:
Error: Unbound module Hello_world
OPT failed on "examples/.patobuild/hello_world_.ml"...
```

**Comment by rlepigre** [comment]
Note that there is still a problem if the current directory contains a source file with the same name as (on of the) file(s) you are compiling and that is itself in a sub-directory. The reason is, I don't know how to tell OCaml not to search `.` first (or at all). Not sure if that's even possible currently, but I did not look too hard.

**Comment by ghuysmans** [comment]
The build order is wrong, here's a small test case:
```
$ echo root >doc.txp
$ mkdir sub
$ echo sub >sub/doc.txp
$ patoline sub/doc.txp 
[PPP] pa_patoline --main --build-dir sub/.patobuild sub/doc.txp > sub/.patobuild/doc.ml
[DEP] ocamldep -I sub -one-line -native -ml-synonym .txp sub/.patobuild/doc_.ml
[DEP] ocamldep -I sub -one-line -native -ml-synonym .txp .patobuild/doc.ml
[OPT] ocamlfind ocamlopt -package patoline.patoraw,patoline.typography,patoline.format.DefaultFormat,earley,earley.str,patoline.driver.Pdf -I sub/.patobuild -c -o sub/.patobuild/doc_.cmx sub/.patobuild/doc_.ml
File "sub/.patobuild/doc_.ml", line 22, characters 15-27:
Error: Unbound module Doc
OPT failed on "sub/.patobuild/doc_.ml"..
```
I expected `sub/.patobuild/doc.ml` as the last argument of this command, maybe that's not an issue:
```
[DEP] ocamldep -I sub -one-line -native -ml-synonym .txp .patobuild/doc.ml
```
Most importantly, the command before this one tells us that `doc_.cmx` depends on `doc.cmx`, but patoline builds the former first: this can't possibly work! My guess is that it internally manipulates badly reconstructed paths, so that it only _thinks_ that dependencies are honored.

The build order is different when building the file in the current directory (`doc.cmx`, then `doc_.cmx`):
```
$ patoline doc.txp 
[PPP] pa_patoline --main --build-dir .patobuild doc.txp > .patobuild/doc.ml
[DEP] ocamldep -I . -one-line -native -ml-synonym .txp .patobuild/doc_.ml
[DEP] ocamldep -I . -one-line -native -ml-synonym .txp .patobuild/doc.ml
[OPT] ocamlfind ocamlopt -package patoline.patoraw,patoline.typography,patoline.format.DefaultFormat,earley,earley.str,patoline.driver.Pdf -I .patobuild -c -o .patobuild/doc.cmx .patobuild/doc.ml
[OPT] ocamlfind ocamlopt -package patoline.patoraw,patoline.typography,patoline.format.DefaultFormat,earley,earley.str,patoline.driver.Pdf -I .patobuild -c -o .patobuild/doc_.cmx .patobuild/doc_.ml
[LNK] ocamlfind ocamlopt -package patoline.patoraw,patoline.typography,patoline.format.DefaultFormat,earley,earley.str,patoline.driver.Pdf -I .patobuild -o .patobuild/doc_.opt -linkpkg .patobuild/doc.cmx .patobuild/doc_.cmx
[RUN] .patobuild/doc_.opt
Pass number 0
Optimization starts: 0.004000 s
Optimization ends: 0.004000 s
```

**Comment by rlepigre** [comment]
I don't think that there is any issue here, except the fact that the OCaml search path first tries the current directory (although it should not, but I don't know how to prevent that).

Let me give you a minimal example, in the following setup (in an empty directory):
```bash
$ mkdir sub
$ touch a.ml
$ echo "open A" > b.ml
$ cp a.ml b.ml sub/
```
Now, in our case, we expect the `open A` of `b.ml` and `sub/b.ml` to refer to the corresponding files, in the corresponding directory. 

However, if you use `ocamldep` to get the dependencies, you get the following result.
```bash
$ ocamldep -I . -one-line -native b.ml
b.cmx : a.cmx
```
That is exactly what we expect, but note that the `-I .` is not actually necessary.

However, the second test does not have the expected result.
```bash
$ ocamldep -I sub -one-line -native sub/b.ml
sub/b.cmx : a.cmx
```
Here, `sub/b.cmx` is said to depends on `a.cmx`, whereas it should depend on `sub/a.cmx`. The problem here is that `ocamldep` searches the "path" in this order:
 - current directory first (that's what we would like to avoid),
 - directories given with the `-I` option in order,
 - the OCaml library directory.

**Comment by ghuysmans** [comment]
Oh, you're right. `ocamldep`'s manual doesn't insist on the order, but it says that OCaml libraries are ignored (emphasis mine):

> _-I directory_
> Add the given directory to the list of directories searched for source files. If a source file `foo.ml` mentions an external compilation unit Bar, a dependency on that unit's interface `bar.cmi` is generated only if the source for bar is found in the current directory or in one of the directories specified with `-I`. **Otherwise, Bar is assumed to be a module from the standard library, and no dependencies are generated.** (...)
