### ISSUE TITLE
Compile patobook gives error

### ISSUE THREAD

**Issue by zejal** [patoline/patoline#7]
Synced to latest. Trying: make in patobook directory I get some warnings and finally an error:

Parse error: file "Programming.txp", line 103, character 3.

Anything I am doing wrong?
Thanks a lot

Joseph

**Comment by flh** [comment]
This does not reproduce on my computer. I really suspect a Windows end-of-line issue, since the reported position corresponds to a verbatim ### start tag in Programming.txp, and pa_patoline really expects "\n" after this (pa_patoline.ml:301).

**Comment by rlepigre** [comment]
I do not have time to investigate right now, bug @flh is certainly right. We never tested Patoline, nor its parser, on Windows. There are probably a few places where we need to adapt the parsing rules to allow for an optional `\r` character.

By the way, note that the Patobook is completely outdated. We will try to work on that soon so that we have a decent user manual.
